name: CI

on:
  pull_request:
  push:
    branches:
      - main

jobs:
  build:

    runs-on: macos-latest

    strategy:
      fail-fast: false
      matrix:
        formula:
          - buckup
          - heroku-audit

    steps:
    - uses: actions/checkout@v4
    - name: Install custom tap
      run: |
        mkdir -p /usr/local/Homebrew/Library/Taps/$GITHUB_REPOSITORY
        cp -r * /usr/local/Homebrew/Library/Taps/$GITHUB_REPOSITORY/
    - name: Install ${{ matrix.formula }}
      run: brew install $GITHUB_REPOSITORY/${{ matrix.formula }}
    - name: Test ${{ matrix.formula }}
      run: brew test $GITHUB_REPOSITORY/${{ matrix.formula }}
